server:
  port: 8100

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    rce:
      path: /rce/**
      url: http://localhost:5000
    rooms:
      path: /rooms/**
      url: http://localhost:5001
    content:
      path: /content/**
      url: http://localhost:5002
    auth:
      path: /auth/**
      url: http://localhost:5003

  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 5000


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


security:
  oauth2:
    resource:
      jwt:
        key-value: 0cec2ac0c09602448541f423f31e5d4fc2c6e040